source 'https://rubygems.org'

gem 'cinch', '~> 2.0.12'
gem 'nokogiri', '~> 1.6.1'
gem 'capistrano', '~> 3.1.0'
gem 'capistrano-rvm', '~> 0.1.1'
gem 'active_hash', '~> 1.2.3'
gem 'twss'
gem 'microsoft_translator'
# gem 'debugger'